import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // --- General & Layout ---
  mainContainer: { flex: 1, backgroundColor: '#fff' },
  headerDark: { backgroundColor: '#fff', height: 120, justifyContent: 'center', alignItems: 'center', paddingTop: 20 },
  logoSmall: { width: 50, height: 60 },
  
  // --- Bottom Nav ---
  bottomNav: { flexDirection: 'row', backgroundColor: '#2C3E50', height: 70, justifyContent: 'space-around', alignItems: 'center', paddingBottom: 10 },
  navItem: { alignItems: 'center' },
  navText: { color: '#fff', fontSize: 10, marginTop: 2 },

  // --- Splash Screen ---
  splashContainer: { flex: 1, backgroundColor: '#fff', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 50 },
  splashCenter: { alignItems: 'center', marginTop: 150 },
  logoLarge: { width: 120, height: 150, marginBottom: 20 },
  splashTitle: { fontSize: 26, fontWeight: '900', color: '#FF9800', letterSpacing: 1 },
  loadingWrapper: { marginBottom: 30, padding: 10 },
  loadingText: { fontSize: 16, color: '#FF9800', fontWeight: '600' },

  // --- Login Screen ---
  formContainer: { paddingHorizontal: 40, paddingTop: 40 },
  formCardContainer: { width: '100%', maxWidth: 400, backgroundColor: '#f8f9fa', borderRadius: 20, paddingVertical: 40, paddingHorizontal: 25, marginTop: 20, elevation: 5, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 12, borderWidth: 1, borderColor: '#e8e8e8' },
  formTitle: { textAlign: 'center', fontSize: 28, fontWeight: '700', marginBottom: 32, color: '#2C3E50', letterSpacing: 0.5 },
  label: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  input: { backgroundColor: '#fff', height: 45, marginBottom: 20, paddingHorizontal: 16, borderRadius: 8, borderWidth: 1, borderColor: '#ddd', fontSize: 16 },
  inputWithIcon: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#ddd', borderRadius: 8, flexDirection: 'row', alignItems: 'center', marginBottom: 24 },
  inputField: { flex: 1, height: 48, paddingLeft: 16, fontSize: 16 },
  eyeIconButton: { paddingHorizontal: 12, height: 48, justifyContent: 'center' },
  eyeIcon: { fontSize: 22, color: '#666' },
  rememberContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 30 },
  checkboxBox: { width: 15, height: 15, backgroundColor: '#ccc', marginRight: 10 },
  rememberText: { fontSize: 12, fontWeight: 'bold' },
  primaryButton: { backgroundColor: '#FF9800', paddingVertical: 12, alignItems: 'center', marginBottom: 12, borderRadius: 8 },
  primaryButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  secondaryButton: { backgroundColor: '#2C3E50', paddingVertical: 12, alignItems: 'center', marginBottom: 10, borderRadius: 8 },
  secondaryButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  forgotText: { textAlign: 'center', fontSize: 14, fontWeight: '600', marginTop: 20, color: '#FF9800' },

  // --- Home Screen ---
  homeBackdropTop: { position: 'absolute', top: -120, right: -80, width: 280, height: 280, borderRadius: 140, backgroundColor: '#fff' },
  homeBackdropBottom: { position: 'absolute', bottom: 90, left: -70, width: 220, height: 220, borderRadius: 110, backgroundColor: '#fff' },
  homeScrollContent: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 100 },
  homeHero: { marginTop: 10, marginBottom: 20 },
  homeEyebrow: { color: '#E67E22', fontWeight: '700', fontSize: 13, letterSpacing: 1 },
  homeTitle: { color: '#1F2D3D', fontSize: 34, fontWeight: '900', marginTop: 6 },
  homeSubtitle: { color: '#5F6E7A', fontSize: 15, lineHeight: 22, marginTop: 8, maxWidth: '90%' },
  sosCircleButton: { width: 220, height: 220, borderRadius: 110, backgroundColor: '#D64545', alignSelf: 'center', justifyContent: 'center', alignItems: 'center', marginTop: 8, marginBottom: 24, elevation: 8, shadowColor: '#8E1A1A', shadowOpacity: 0.3, shadowRadius: 12 },
  sosCircleTitle: { color: '#fff', fontSize: 26, fontWeight: '900', marginBottom: 8 },
  sosCircleHint: { color: '#FFE5E5', fontSize: 12, marginTop: 8 },
  quickLabel: { color: '#1F2D3D', fontSize: 18, fontWeight: '800', marginBottom: 12 },
  directoryGrid: { flexDirection: 'row', gap: 12 },
  dirCard: { flex: 1, borderRadius: 18, paddingVertical: 16, paddingHorizontal: 10, alignItems: 'center' },
  policeCard: { backgroundColor: '#2C3E50' },
  fireCard: { backgroundColor: '#E36A20' },
  medicCard: { backgroundColor: '#2AAFC2' },
  dirIconBubble: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#fff', justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  dirCardTitle: { color: '#fff', fontWeight: '800', fontSize: 15 },
  dirCardMeta: { color: '#F3F6F8', fontSize: 11, marginTop: 4 },

  // --- Profile Screen ---
  profileBackdropTop: { position: 'absolute', top: -130, left: -70, width: 260, height: 260, borderRadius: 130, backgroundColor: '#fff' },
  profileBackdropBottom: { position: 'absolute', bottom: 90, right: -80, width: 240, height: 240, borderRadius: 120, backgroundColor: '#fff' },
  profileScrollContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 100 },
  profileTitle: { fontSize: 32, fontWeight: '900', color: '#1F2D3D' },
  profileSubtitle: { fontSize: 14, color: '#647483', marginTop: 8, marginBottom: 16 },
  profileCard: { backgroundColor: '#F9FBFF', borderRadius: 22, alignItems: 'center', paddingVertical: 26, paddingHorizontal: 20, borderWidth: 1, borderColor: '#E5ECF3', elevation: 4, shadowColor: '#5D6B79', shadowOpacity: 0.12, shadowRadius: 10 },
  avatarPlaceholder: { width: 102, height: 102, borderRadius: 51, backgroundColor: '#DDE7F2', marginBottom: 12, alignItems: 'center', justifyContent: 'center' },
  profileAvatarImage: { width: 102, height: 102, borderRadius: 51 },
  profileName: { fontSize: 24, color: '#233445', fontWeight: '800', marginTop: 4 },
  profileEmail: { fontSize: 14, color: '#778797', marginTop: 4 },
  profileEditChip: { marginTop: 14, backgroundColor: '#2C3E50', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8 },
  profileEditChipText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  profileMenu: { marginTop: 18, gap: 12 },
  profileActionRow: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#E8EDF3', paddingVertical: 14, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' },
  profileIconWrap: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#EEF3F8', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  profileActionText: { flex: 1, color: '#2E3D4B', fontSize: 15, fontWeight: '700' },
  profileLogoutBtn: { marginTop: 16, backgroundColor: '#FFF5F5', borderRadius: 14, borderWidth: 1, borderColor: '#F2D0D0', paddingVertical: 14, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' },
  profileLogoutIconWrap: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#FDE7E7', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  profileLogoutText: { color: '#C84444', fontSize: 15, fontWeight: '800' },
  profileModalOverlay: { flex: 1, backgroundColor: 'rgba(21, 33, 45, 0.45)', justifyContent: 'center', paddingHorizontal: 20 },
  profileModalCard: { backgroundColor: '#fff', borderRadius: 18, paddingHorizontal: 18, paddingVertical: 20, borderWidth: 1, borderColor: '#E5ECF3' },
  profileModalTitle: { fontSize: 22, fontWeight: '800', color: '#1F2D3D', marginBottom: 16 },
  profileModalLabel: { fontSize: 13, color: '#4C5C6C', fontWeight: '700', marginBottom: 6, marginTop: 8 },
  profileModalInput: { borderWidth: 1, borderColor: '#DCE5EE', borderRadius: 10, height: 44, paddingHorizontal: 12, color: '#1F2D3D', fontSize: 14, backgroundColor: '#F9FBFF' },
  profileImagePickerBtn: { borderRadius: 10, borderWidth: 1, borderColor: '#DCE5EE', backgroundColor: '#F9FBFF', paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  profileImagePickerBtnText: { color: '#2E3D4B', fontWeight: '700', fontSize: 14 },
  profileModalImagePreview: { width: 96, height: 96, borderRadius: 48, marginTop: 10, alignSelf: 'center' },
  profileModalHelperText: { color: '#5F6E7A', fontSize: 12, marginTop: 8 },
  profileModalActions: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 18, gap: 10 },
  profileModalCancelBtn: { borderRadius: 10, borderWidth: 1, borderColor: '#D3DDE7', paddingVertical: 10, paddingHorizontal: 16, backgroundColor: '#F6F9FC' },
  profileModalCancelText: { color: '#415467', fontWeight: '700', fontSize: 14 },
  profileModalSaveBtn: { borderRadius: 10, paddingVertical: 10, paddingHorizontal: 18, backgroundColor: '#2C3E50' },
  profileModalSaveText: { color: '#fff', fontWeight: '700', fontSize: 14 },

  // --- Contacts Screen ---
  contactsContent: { flex: 1, padding: 20 },
  contactsBackdropTop: { position: 'absolute', top: -110, right: -80, width: 250, height: 250, borderRadius: 125, backgroundColor: '#fff' },
  contactsBackdropBottom: { position: 'absolute', bottom: 90, left: -70, width: 220, height: 220, borderRadius: 110, backgroundColor: '#fff' },
  contactsScrollContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 100 },
  contactsTitle: { fontSize: 32, fontWeight: '900', color: '#1F2D3D' },
  contactsSubtitle: { fontSize: 14, color: '#627484', marginTop: 8, marginBottom: 18 },
  contactCardModern: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E7EDF4', paddingVertical: 14, paddingHorizontal: 12, marginBottom: 12, flexDirection: 'row', alignItems: 'center', elevation: 2, shadowColor: '#667788', shadowOpacity: 0.08, shadowRadius: 6 },
  contactAvatarWrap: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#EDF3F9', justifyContent: 'center', alignItems: 'center' },
  contactCard: { backgroundColor: '#FF9800', flexDirection: 'row', alignItems: 'center', padding: 15, borderRadius: 15, marginBottom: 15 },
  contactInfo: { flex: 1, marginLeft: 15 },
  contactNameModern: { color: '#223446', fontWeight: '800', fontSize: 15 },
  contactPhoneModern: { color: '#6F8191', fontSize: 12, marginTop: 3 },
  contactDeleteBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#FCEBEC', justifyContent: 'center', alignItems: 'center' },
  contactName: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  contactPhone: { color: '#fff', fontSize: 12 },
  addContactBtn: { marginTop: 6, backgroundColor: '#2C3E50', borderRadius: 12, paddingVertical: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  addContactBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  addContactText: { color: '#4CAF50', fontWeight: 'bold', textAlign: 'center', fontSize: 16, marginTop: 10 }
});

export default styles;
