import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  // --- General & Layout ---
  mainContainer: { flex: 1, backgroundColor: '#fff' },
  headerDark: { backgroundColor: '#fff', height: 120, justifyContent: 'center', alignItems: 'center', paddingTop: 20 },
  logoSmall: { width: 50, height: 60 },
  
  // --- Bottom Nav ---
  bottomNav: { flexDirection: 'row', backgroundColor: '#2C3E50', height: 70, justifyContent: 'space-around', alignItems: 'center', paddingBottom: 10 },
  navItem: { alignItems: 'center' },
  navText: { color: '#fff', fontSize: 10, marginTop: 2 },

  // --- Splash Screen ---
  splashContainer: { flex: 1, backgroundColor: '#fff', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 50 },
  splashCenter: { alignItems: 'center', marginTop: 150 },
  logoLarge: { width: 120, height: 150, marginBottom: 20 },
  splashTitle: { fontSize: 26, fontWeight: '900', color: '#FF9800', letterSpacing: 1 },
  loadingWrapper: { marginBottom: 30, padding: 10 },
  loadingText: { fontSize: 16, color: '#FF9800', fontWeight: '600' },

  // --- Login Screen ---
  formContainer: { paddingHorizontal: 40, paddingTop: 40 },
  formCardContainer: { width: '100%', maxWidth: 400, backgroundColor: '#f8f9fa', borderRadius: 20, paddingVertical: 40, paddingHorizontal: 25, marginTop: 20, elevation: 5, shadowColor: '#000', shadowOpacity: 0.12, shadowRadius: 12, borderWidth: 1, borderColor: '#e8e8e8' },
  formTitle: { textAlign: 'center', fontSize: 28, fontWeight: '700', marginBottom: 32, color: '#2C3E50', letterSpacing: 0.5 },
  label: { fontSize: 16, fontWeight: 'bold', color: '#333', marginBottom: 8 },
  input: { backgroundColor: '#fff', height: 45, marginBottom: 20, paddingHorizontal: 16, borderRadius: 8, borderWidth: 1, borderColor: '#ddd', fontSize: 16 },
  inputWithIcon: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#ddd', borderRadius: 8, flexDirection: 'row', alignItems: 'center', marginBottom: 24 },
  inputField: { flex: 1, height: 48, paddingLeft: 16, fontSize: 16 },
  eyeIconButton: { paddingHorizontal: 12, height: 48, justifyContent: 'center' },
  eyeIcon: { fontSize: 22, color: '#666' },
  rememberContainer: { flexDirection: 'row', alignItems: 'center', marginBottom: 30 },
  checkboxBox: { width: 15, height: 15, backgroundColor: '#ccc', marginRight: 10 },
  rememberText: { fontSize: 12, fontWeight: 'bold' },
  primaryButton: { backgroundColor: '#FF9800', paddingVertical: 16, paddingHorizontal: 20, alignItems: 'center', marginBottom: 12, borderRadius: 8 },
  primaryButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16, lineHeight: 22 },
  secondaryButton: { backgroundColor: '#2C3E50', paddingVertical: 16, paddingHorizontal: 20, alignItems: 'center', marginBottom: 10, borderRadius: 8 },
  secondaryButtonText: { color: '#fff', fontWeight: 'bold', fontSize: 16, lineHeight: 22 },
  forgotText: { textAlign: 'center', fontSize: 14, fontWeight: '600', marginTop: 20, color: '#FF9800' },

  // --- Home Screen ---
  homeBackdropTop: { position: 'absolute', top: -120, right: -80, width: 280, height: 280, borderRadius: 140, backgroundColor: '#fff' },
  homeBackdropBottom: { position: 'absolute', bottom: 90, left: -70, width: 220, height: 220, borderRadius: 110, backgroundColor: '#fff' },
  homeScrollContent: { paddingHorizontal: 20, paddingTop: 10, paddingBottom: 100 },
  homeHero: { marginTop: 20, marginBottom: 32, paddingVertical: 12 },
  homeEyebrow: { color: '#FF9800', fontWeight: '700', fontSize: 12, letterSpacing: 2, textTransform: 'uppercase', marginBottom: 4 },
  homeTitle: { color: '#1F2D3D', fontSize: 40, fontWeight: '900', marginTop: 12, lineHeight: 48, letterSpacing: -0.5 },
  homeSubtitle: { color: '#6B7F94', fontSize: 16, lineHeight: 24, marginTop: 14, maxWidth: '90%', fontWeight: '500' },
  sosCircleButton: { width: 220, height: 220, borderRadius: 110, backgroundColor: '#D64545', alignSelf: 'center', justifyContent: 'center', alignItems: 'center', marginTop: 8, marginBottom: 24, elevation: 8, shadowColor: '#8E1A1A', shadowOpacity: 0.3, shadowRadius: 12 },
  sosCircleTitle: { color: '#fff', fontSize: 26, fontWeight: '900', marginBottom: 8 },
  sosCircleHint: { color: '#FFE5E5', fontSize: 12, marginTop: 8 },
  quickLabel: { color: '#1F2D3D', fontSize: 18, fontWeight: '800', marginBottom: 12 },
  directoryGrid: { flexDirection: 'row', gap: 12 },
  dirCard: { flex: 1, borderRadius: 18, paddingVertical: 16, paddingHorizontal: 10, alignItems: 'center' },
  policeCard: { backgroundColor: '#2C3E50' },
  fireCard: { backgroundColor: '#E36A20' },
  medicCard: { backgroundColor: '#2AAFC2' },
  dirIconBubble: { width: 54, height: 54, borderRadius: 27, backgroundColor: '#fff', justifyContent: 'center', alignItems: 'center', marginBottom: 10 },
  dirCardTitle: { color: '#fff', fontWeight: '800', fontSize: 15 },
  dirCardMeta: { color: '#F3F6F8', fontSize: 11, marginTop: 4 },
  myReportsCard: { marginTop: 16, backgroundColor: '#F9FBFF', borderRadius: 16, borderWidth: 1, borderColor: '#DCE5EE', paddingVertical: 14, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', gap: 12 },
  myReportsCardIconWrap: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#E7EEF5', justifyContent: 'center', alignItems: 'center' },
  myReportsCardTitle: { color: '#213444', fontSize: 15, fontWeight: '800' },
  myReportsCardMeta: { color: '#6F8191', fontSize: 12, marginTop: 3 },

  // --- Profile Screen ---
  profileBackdropTop: { position: 'absolute', top: -130, left: -70, width: 260, height: 260, borderRadius: 130, backgroundColor: '#fff' },
  profileBackdropBottom: { position: 'absolute', bottom: 90, right: -80, width: 240, height: 240, borderRadius: 120, backgroundColor: '#fff' },
  profileScrollContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 100 },
  profileTitle: { fontSize: 32, fontWeight: '900', color: '#1F2D3D' },
  profileSubtitle: { fontSize: 14, color: '#647483', marginTop: 8, marginBottom: 16 },
  profileCard: { backgroundColor: '#F9FBFF', borderRadius: 22, alignItems: 'center', paddingVertical: 26, paddingHorizontal: 20, borderWidth: 1, borderColor: '#E5ECF3', elevation: 4, shadowColor: '#5D6B79', shadowOpacity: 0.12, shadowRadius: 10 },
  avatarPlaceholder: { width: 102, height: 102, borderRadius: 51, backgroundColor: '#DDE7F2', marginBottom: 12, alignItems: 'center', justifyContent: 'center' },
  profileAvatarImage: { width: 102, height: 102, borderRadius: 51 },
  profileName: { fontSize: 24, color: '#233445', fontWeight: '800', marginTop: 4 },
  profileEmail: { fontSize: 14, color: '#778797', marginTop: 4 },
  profileEditChip: { marginTop: 14, backgroundColor: '#2C3E50', borderRadius: 20, paddingHorizontal: 16, paddingVertical: 8 },
  profileEditChipText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  profileMenu: { marginTop: 18, gap: 12 },
  profileActionRow: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#E8EDF3', paddingVertical: 14, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' },
  profileIconWrap: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#EEF3F8', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  profileActionText: { flex: 1, color: '#2E3D4B', fontSize: 15, fontWeight: '700' },
  profileLogoutBtn: { marginTop: 16, backgroundColor: '#FFF5F5', borderRadius: 14, borderWidth: 1, borderColor: '#F2D0D0', paddingVertical: 14, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' },
  profileLogoutIconWrap: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#FDE7E7', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  profileLogoutText: { color: '#C84444', fontSize: 15, fontWeight: '800' },
  profileModalOverlay: { flex: 1, backgroundColor: 'rgba(21, 33, 45, 0.45)', justifyContent: 'center', paddingHorizontal: 20 },
  profileModalCard: { backgroundColor: '#fff', borderRadius: 18, paddingHorizontal: 18, paddingVertical: 20, borderWidth: 1, borderColor: '#E5ECF3' },
  profileModalTitle: { fontSize: 22, fontWeight: '800', color: '#1F2D3D', marginBottom: 16 },
  profileModalLabel: { fontSize: 13, color: '#4C5C6C', fontWeight: '700', marginBottom: 6, marginTop: 8 },
  profileModalInput: { borderWidth: 1, borderColor: '#DCE5EE', borderRadius: 10, height: 44, paddingHorizontal: 12, color: '#1F2D3D', fontSize: 14, backgroundColor: '#F9FBFF' },
  profileImagePickerBtn: { borderRadius: 10, borderWidth: 1, borderColor: '#DCE5EE', backgroundColor: '#F9FBFF', paddingVertical: 12, alignItems: 'center', justifyContent: 'center' },
  profileImagePickerBtnText: { color: '#2E3D4B', fontWeight: '700', fontSize: 14 },
  profileModalImagePreview: { width: 96, height: 96, borderRadius: 48, marginTop: 10, alignSelf: 'center' },
  profileModalHelperText: { color: '#5F6E7A', fontSize: 12, marginTop: 8 },
  profileModalActions: { flexDirection: 'row', justifyContent: 'flex-end', marginTop: 18, gap: 10 },
  profileModalCancelBtn: { borderRadius: 10, borderWidth: 1, borderColor: '#D3DDE7', paddingVertical: 10, paddingHorizontal: 16, backgroundColor: '#F6F9FC' },
  profileModalCancelText: { color: '#415467', fontWeight: '700', fontSize: 14 },
  profileModalSaveBtn: { borderRadius: 10, paddingVertical: 10, paddingHorizontal: 18, backgroundColor: '#2C3E50' },
  profileModalSaveText: { color: '#fff', fontWeight: '700', fontSize: 14 },

  // --- Contacts Screen ---
  contactsContent: { flex: 1, padding: 20 },
  contactsBackdropTop: { position: 'absolute', top: -110, right: -80, width: 250, height: 250, borderRadius: 125, backgroundColor: '#fff' },
  contactsBackdropBottom: { position: 'absolute', bottom: 90, left: -70, width: 220, height: 220, borderRadius: 110, backgroundColor: '#fff' },
  contactsScrollContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 100 },
  contactsTitle: { fontSize: 32, fontWeight: '900', color: '#1F2D3D' },
  contactsSubtitle: { fontSize: 14, color: '#627484', marginTop: 8, marginBottom: 18 },
  contactCardModern: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E7EDF4', paddingVertical: 14, paddingHorizontal: 12, marginBottom: 12, flexDirection: 'row', alignItems: 'center', elevation: 2, shadowColor: '#667788', shadowOpacity: 0.08, shadowRadius: 6 },
  contactAvatarWrap: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#EDF3F9', justifyContent: 'center', alignItems: 'center' },
  contactCard: { backgroundColor: '#FF9800', flexDirection: 'row', alignItems: 'center', padding: 15, borderRadius: 15, marginBottom: 15 },
  contactInfo: { flex: 1, marginLeft: 15 },
  contactNameModern: { color: '#223446', fontWeight: '800', fontSize: 15 },
  contactPhoneModern: { color: '#6F8191', fontSize: 12, marginTop: 3 },
  contactDeleteBtn: { width: 34, height: 34, borderRadius: 17, backgroundColor: '#FCEBEC', justifyContent: 'center', alignItems: 'center' },
  contactName: { color: '#fff', fontWeight: 'bold', fontSize: 16 },
  contactPhone: { color: '#fff', fontSize: 12 },
  addContactBtn: { marginTop: 6, backgroundColor: '#2C3E50', borderRadius: 12, paddingVertical: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8 },
  addContactBtnText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  addContactText: { color: '#4CAF50', fontWeight: 'bold', textAlign: 'center', fontSize: 16, marginTop: 10 },

  // --- Modal Styles ---
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { backgroundColor: '#fff', borderRadius: 20, padding: 25, width: '90%', maxWidth: 400, elevation: 10, shadowColor: '#000', shadowOpacity: 0.25, shadowRadius: 10 },
  modalTitle: { fontSize: 24, fontWeight: '700', textAlign: 'center', marginBottom: 20, color: '#2C3E50' },
  modalButtons: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 24, gap: 12 },

  // --- Hotline Screen ---
  hotlineCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E7EDF4', paddingVertical: 14, paddingHorizontal: 14, marginBottom: 12, flexDirection: 'row', alignItems: 'center', elevation: 2, shadowColor: '#667788', shadowOpacity: 0.08, shadowRadius: 6 },
  hotlineIconWrap: { width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' },
  hotlineInfo: { flex: 1, marginLeft: 14 },
  hotlineLabel: { color: '#223446', fontWeight: '800', fontSize: 15 },
  hotlineNumber: { color: '#6F8191', fontSize: 13, marginTop: 3 },
  hotlineCallBtn: { width: 40, height: 40, borderRadius: 20, backgroundColor: '#E8F8EF', justifyContent: 'center', alignItems: 'center' },

  // --- Report Incident Screen ---
  incidentTypeGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 8 },
  incidentTypeChip: { paddingVertical: 10, paddingHorizontal: 16, borderRadius: 20, borderWidth: 1.5, borderColor: '#DCE5EE', backgroundColor: '#F9FBFF' },
  incidentTypeChipActive: { borderColor: '#FF9800', backgroundColor: '#FFF3E0' },
  incidentTypeText: { color: '#5F6E7A', fontWeight: '700', fontSize: 13 },
  incidentTypeTextActive: { color: '#E65100' },
  incidentTextArea: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#DCE5EE', borderRadius: 12, padding: 14, fontSize: 15, minHeight: 120, color: '#1F2D3D' },
  incidentLocationRow: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFF8F0', borderRadius: 12, padding: 14, gap: 10, borderWidth: 1, borderColor: '#FFE0B2' },
  incidentLocationText: { flex: 1, color: '#5F6E7A', fontSize: 14, fontWeight: '600' },
  incidentPhotoPickerBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, borderWidth: 1, borderColor: '#DCE5EE', backgroundColor: '#F9FBFF', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 12 },
  incidentPhotoPickerText: { color: '#2C3E50', fontSize: 14, fontWeight: '700' },
  incidentPhotoGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 10 },
  incidentPhotoItem: { width: 86, height: 86, borderRadius: 10, overflow: 'hidden', position: 'relative', borderWidth: 1, borderColor: '#DCE5EE' },
  incidentPhotoPreview: { width: '100%', height: '100%' },
  incidentPhotoRemoveBtn: { position: 'absolute', top: 4, right: 4, width: 18, height: 18, borderRadius: 9, backgroundColor: 'rgba(44, 62, 80, 0.85)', alignItems: 'center', justifyContent: 'center' },
  incidentPhotoHint: { color: '#6F8191', marginTop: 10, fontSize: 12, fontWeight: '600' },

  // --- My Reports Screen ---
  myReportsRefreshBtn: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: '#EEF3F8', borderRadius: 16, paddingVertical: 8, paddingHorizontal: 12, marginBottom: 14 },
  myReportsRefreshText: { color: '#2C3E50', fontSize: 13, fontWeight: '700' },
  myReportsCenterState: { marginTop: 36, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  myReportsStateText: { marginTop: 10, color: '#6F8191', fontSize: 14, fontWeight: '600', textAlign: 'center' },
  myReportCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E7EDF4', paddingVertical: 14, paddingHorizontal: 14, marginBottom: 12 },
  myReportHeaderRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  myReportType: { flex: 1, color: '#223446', fontSize: 16, fontWeight: '800' },
  myReportStatusPill: { backgroundColor: '#FFF3E0', borderWidth: 1, borderColor: '#FFD8A8', borderRadius: 999, paddingHorizontal: 10, paddingVertical: 4 },
  myReportStatusText: { color: '#A85A00', fontSize: 10, fontWeight: '800' },
  myReportStatusSubmitted: { backgroundColor: '#FFF3E0', borderColor: '#FFD8A8' },
  myReportStatusSubmittedText: { color: '#A85A00' },
  myReportStatusProgress: { backgroundColor: '#EAF4FF', borderColor: '#B8D8FF' },
  myReportStatusProgressText: { color: '#1E5EA8' },
  myReportStatusResolved: { backgroundColor: '#E8F8EF', borderColor: '#BEE9CF' },
  myReportStatusResolvedText: { color: '#1A7A42' },
  myReportMetaRow: { marginTop: 10, flexDirection: 'row', alignItems: 'center' },
  myReportPriorityPill: { borderRadius: 999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 4 },
  myReportPriorityText: { fontSize: 10, fontWeight: '800' },
  myReportPriorityNormal: { backgroundColor: '#F1F4F7', borderColor: '#DCE5EE' },
  myReportPriorityNormalText: { color: '#546575' },
  myReportPriorityHigh: { backgroundColor: '#FFF0F0', borderColor: '#FFD1D1' },
  myReportPriorityHighText: { color: '#B53838' },
  myReportSyncPill: { marginLeft: 8, borderRadius: 999, borderWidth: 1, paddingHorizontal: 10, paddingVertical: 4 },
  myReportSyncText: { fontSize: 10, fontWeight: '800' },
  myReportSyncSynced: { backgroundColor: '#E8F8EF', borderColor: '#BEE9CF' },
  myReportSyncSyncedText: { color: '#1A7A42' },
  myReportSyncSyncing: { backgroundColor: '#EAF4FF', borderColor: '#B8D8FF' },
  myReportSyncSyncingText: { color: '#1E5EA8' },
  myReportSyncPending: { backgroundColor: '#FFF0F0', borderColor: '#FFD1D1' },
  myReportSyncPendingText: { color: '#B53838' },
  myReportSyncLocalOnly: { backgroundColor: '#F3F4F6', borderColor: '#DBE0E6' },
  myReportSyncLocalOnlyText: { color: '#4F5E6D' },
  myReportSyncError: { marginTop: 8, color: '#B53838', fontSize: 12, fontWeight: '600' },
  myReportTime: { marginTop: 8, color: '#6F8191', fontSize: 12, fontWeight: '600' },
  myReportDescription: { marginTop: 10, color: '#2C3E50', fontSize: 14, lineHeight: 20, fontWeight: '500' },
  myReportLocationRow: { marginTop: 10, flexDirection: 'row', alignItems: 'center', gap: 6 },
  myReportLocationText: { color: '#5F6E7A', fontSize: 12, fontWeight: '600' },
  myReportPhotoGrid: { marginTop: 12, flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  myReportPhoto: { width: 86, height: 86, borderRadius: 10, borderWidth: 1, borderColor: '#DCE5EE' },
  myReportNoPhotos: { marginTop: 12, color: '#8A96A3', fontSize: 12, fontWeight: '600' },
  myReportsLoadMoreBtn: { marginTop: 2, marginBottom: 6, alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 8, backgroundColor: '#EEF3F8', borderRadius: 18, paddingHorizontal: 14, paddingVertical: 10 },
  myReportsLoadMoreText: { color: '#2C3E50', fontSize: 13, fontWeight: '700' },
  photoPreviewOverlay: { flex: 1, backgroundColor: 'rgba(10, 20, 31, 0.88)', justifyContent: 'center', alignItems: 'center', paddingHorizontal: 16 },
  photoPreviewContent: { width: '100%', maxWidth: 520, height: '72%', backgroundColor: '#101A24', borderRadius: 14, overflow: 'hidden', borderWidth: 1, borderColor: '#33475A' },
  photoPreviewImage: { width: '100%', height: '100%' },
  photoPreviewCloseBtn: { position: 'absolute', top: 10, right: 10, width: 34, height: 34, borderRadius: 17, backgroundColor: 'rgba(12, 23, 34, 0.75)', justifyContent: 'center', alignItems: 'center', zIndex: 1 },

  // --- Report Detail Screen ---
  reportDetailTopRow: { marginBottom: 6 },
  reportDetailBackBtn: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#EEF3F8', borderRadius: 16, paddingVertical: 7, paddingHorizontal: 10 },
  reportDetailBackText: { color: '#2C3E50', fontSize: 13, fontWeight: '700' },
  reportDetailCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E7EDF4', paddingVertical: 14, paddingHorizontal: 14, marginTop: 4, marginBottom: 12 },
  reportDetailHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  reportDetailType: { flex: 1, color: '#223446', fontSize: 18, fontWeight: '800' },
  reportDetailMeta: { color: '#6F8191', fontSize: 12, fontWeight: '600', marginTop: 8 },
  reportDetailBlock: { marginTop: 14 },
  reportDetailLabel: { color: '#435668', fontSize: 12, fontWeight: '800', marginBottom: 5, letterSpacing: 0.4 },
  reportDetailValue: { color: '#2C3E50', fontSize: 14, lineHeight: 20, fontWeight: '500' },

  // --- GPS Screen ---
  gpsContainer: { flex: 1, paddingHorizontal: 20, paddingTop: 8, paddingBottom: 100 },
  gpsCard: { backgroundColor: '#F9FBFF', borderRadius: 22, borderWidth: 1, borderColor: '#E5ECF3', marginTop: 20, elevation: 4, shadowColor: '#5D6B79', shadowOpacity: 0.12, shadowRadius: 10, overflow: 'hidden' },
  mapContainer: { width: '100%', height: 280, borderRadius: 22 },
  gpsCenterContent: { alignItems: 'center', paddingVertical: 30 },
  gpsLoadingText: { color: '#6B7F94', fontSize: 15, marginTop: 14, fontWeight: '600' },
  gpsErrorText: { color: '#D64545', fontSize: 15, marginTop: 14, fontWeight: '600', textAlign: 'center' },
  gpsIconRow: { marginBottom: 14 },
  gpsCoords: { fontSize: 18, fontWeight: '800', color: '#1F2D3D', textAlign: 'center' },
  gpsAddress: { fontSize: 14, color: '#6B7F94', marginTop: 12, marginBottom: 16, textAlign: 'center', lineHeight: 20, fontWeight: '500', paddingHorizontal: 20 },
  gpsActions: { flexDirection: 'row', gap: 12, marginTop: 16, width: '100%', paddingHorizontal: 20 },
  gpsRefreshBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 20, paddingVertical: 10 },
  gpsRefreshText: { color: '#2C3E50', fontWeight: '700', fontSize: 14 },

  // --- Medical Info Screen ---
  medicalScrollContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 100 },
  medicalCard: { backgroundColor: '#F9FBFF', borderRadius: 18, borderWidth: 1, borderColor: '#E5ECF3', padding: 20, marginTop: 20, marginBottom: 20, gap: 18 },
  medicalFieldGroup: { gap: 8 },
  medicalFieldHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 6 },
  medicalFieldLabel: { fontSize: 14, fontWeight: '700', color: '#2C3E50' },
  medicalInput: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#DCE5EE', borderRadius: 10, paddingHorizontal: 14, paddingVertical: 12, fontSize: 15, color: '#1F2D3D' },
  medicalTextArea: { minHeight: 80, paddingTop: 12, textAlignVertical: 'top' },
  medicalInfoBox: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: '#E0F7FF', borderRadius: 12, padding: 14, gap: 10, marginTop: 16, borderLeftWidth: 4, borderLeftColor: '#2AAFC2' },
  medicalInfoText: { flex: 1, fontSize: 13, color: '#0D5F75', fontWeight: '500', lineHeight: 18 },

  // --- Settings Screen ---
  settingsLoadingState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 20, paddingBottom: 80 },
  settingsLoadingText: { marginTop: 12, color: '#5F6E7A', fontSize: 14, fontWeight: '600' },
  settingsScrollContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 100 },
  settingsTopRow: { marginBottom: 2 },
  settingsBackBtn: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#EEF3F8', borderRadius: 16, paddingVertical: 7, paddingHorizontal: 10 },
  settingsBackBtnText: { color: '#2C3E50', fontSize: 13, fontWeight: '700' },
  settingsSectionCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E7EDF4', paddingHorizontal: 14, paddingVertical: 12, marginBottom: 12, elevation: 2, shadowColor: '#667788', shadowOpacity: 0.08, shadowRadius: 6 },
  settingsDangerCard: { backgroundColor: '#FFF7F7', borderRadius: 16, borderWidth: 1, borderColor: '#F2D0D0', paddingHorizontal: 14, paddingVertical: 12, marginBottom: 12 },
  settingsSectionTitle: { color: '#223446', fontWeight: '800', fontSize: 15, marginBottom: 6 },
  settingsSwitchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, paddingVertical: 8 },
  settingsSwitchContent: { flex: 1, paddingRight: 8 },
  settingsLabel: { color: '#2E3D4B', fontSize: 14, fontWeight: '700' },
  settingsHint: { color: '#6F8191', fontSize: 12, marginTop: 3 },
  settingsDivider: { height: 1, backgroundColor: '#EDF2F7', marginVertical: 4 },
  settingsStepperRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, paddingVertical: 8 },
  settingsStepperControls: { flexDirection: 'row', alignItems: 'center' },
  settingsStepperBtn: { width: 30, height: 30, borderRadius: 15, borderWidth: 1, borderColor: '#DCE5EE', backgroundColor: '#F9FBFF', justifyContent: 'center', alignItems: 'center' },
  settingsStepperValue: { width: 44, textAlign: 'center', color: '#2C3E50', fontWeight: '800', fontSize: 14 },
  settingsActionRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10 },
  settingsActionTextWrap: { flex: 1 },
  settingsActionTitle: { color: '#2E3D4B', fontSize: 14, fontWeight: '700' },
  settingsVersionRow: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 8 },
  settingsVersionText: { color: '#6F8191', fontSize: 12, fontWeight: '600' },
  settingsDangerRow: { backgroundColor: '#FFF5F5', borderRadius: 12, borderWidth: 1, borderColor: '#F2D0D0', paddingVertical: 12, paddingHorizontal: 12, marginTop: 8, flexDirection: 'row', alignItems: 'center' },
  settingsDangerText: { color: '#C84444', fontSize: 14, fontWeight: '800' },

  // SOS Medical Alert
  sosMedicalBox: { backgroundColor: '#FFF3E0', borderRadius: 12, padding: 14, borderWidth: 2, borderColor: '#FF9800', width: '90%', marginTop: 16 },
  sosMedicalTitle: { fontSize: 14, fontWeight: '800', color: '#E65100', marginBottom: 8 },
  sosMedicalLine: { fontSize: 13, color: '#5D4037', fontWeight: '500', marginBottom: 6 },

  // --- Admin Screens ---
  adminBackdropTop: { position: 'absolute', top: -120, right: -80, width: 260, height: 260, borderRadius: 130, backgroundColor: '#fff' },
  adminBackdropBottom: { position: 'absolute', bottom: 90, left: -70, width: 220, height: 220, borderRadius: 110, backgroundColor: '#fff' },
  adminScrollContent: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 100 },
  adminTitle: { fontSize: 32, fontWeight: '900', color: '#1F2D3D' },
  adminSubtitle: { fontSize: 14, color: '#627484', marginTop: 8, marginBottom: 18 },
  adminStatsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 18 },
  adminStatCard: { width: '48%', backgroundColor: '#F9FBFF', borderRadius: 18, borderWidth: 1, borderColor: '#E4ECF3', paddingVertical: 18, paddingHorizontal: 16 },
  adminStatLabel: { color: '#6A7C8D', fontSize: 12, fontWeight: '700', textTransform: 'uppercase', marginBottom: 8 },
  adminStatValue: { color: '#1F2D3D', fontSize: 24, fontWeight: '900' },
  adminActionCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E6EDF3', paddingVertical: 14, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  adminActionIconWrap: { width: 42, height: 42, borderRadius: 21, backgroundColor: '#EEF3F8', justifyContent: 'center', alignItems: 'center', marginRight: 12 },
  adminActionTitle: { flex: 1, color: '#233445', fontSize: 15, fontWeight: '800' },
  adminActionMeta: { color: '#6F8191', fontSize: 12, marginTop: 3 },
  adminListCard: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#E6EDF3', padding: 14, marginBottom: 12 },
  adminListHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', gap: 12 },
  adminListTitle: { color: '#223445', fontSize: 16, fontWeight: '800', flex: 1 },
  adminListMeta: { color: '#6E7F90', fontSize: 12, marginTop: 4 },
  adminListText: { color: '#425464', fontSize: 13, lineHeight: 19, marginTop: 10 },
  adminSearchInput: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#DCE5EE', borderRadius: 10, height: 46, paddingHorizontal: 14, marginBottom: 16, fontSize: 14, color: '#1F2D3D' },
  adminFilterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  adminFilterChip: { paddingVertical: 8, paddingHorizontal: 12, borderRadius: 20, backgroundColor: '#EEF3F8', borderWidth: 1, borderColor: '#DCE5EE' },
  adminFilterChipActive: { backgroundColor: '#2C3E50', borderColor: '#2C3E50' },
  adminFilterChipText: { color: '#3D4F60', fontSize: 12, fontWeight: '700' },
  adminFilterChipTextActive: { color: '#fff' },
  adminBadge: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 14, alignSelf: 'flex-start' },
  adminBadgeText: { fontSize: 11, fontWeight: '800', textTransform: 'uppercase' },
  adminBadgePending: { backgroundColor: '#FFF5E5' },
  adminBadgePendingText: { color: '#D98200' },
  adminBadgeProgress: { backgroundColor: '#E8F1FF' },
  adminBadgeProgressText: { color: '#2D6CDF' },
  adminBadgeResolved: { backgroundColor: '#E8F8EF' },
  adminBadgeResolvedText: { color: '#1F8F55' },
  adminRoleBadge: { paddingVertical: 6, paddingHorizontal: 10, borderRadius: 14, alignSelf: 'flex-start' },
  adminRoleUser: { backgroundColor: '#EEF3F8' },
  adminRoleUserText: { color: '#415467' },
  adminRoleAdmin: { backgroundColor: '#FFEBD2' },
  adminRoleAdminText: { color: '#C76B00' },
  adminInlineActions: { flexDirection: 'row', gap: 8, marginTop: 12, flexWrap: 'wrap' },
  adminSmallButton: { backgroundColor: '#2C3E50', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 12 },
  adminSmallButtonText: { color: '#fff', fontSize: 12, fontWeight: '700' },
  adminSmallOutlineButton: { backgroundColor: '#F7FAFC', borderRadius: 10, paddingVertical: 8, paddingHorizontal: 12, borderWidth: 1, borderColor: '#D8E2EB' },
  adminSmallOutlineButtonText: { color: '#415467', fontSize: 12, fontWeight: '700' },
});

export default styles;
